### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by zhangzhen999** [THUNLP-MT/THUMT#67]
while decoding,the error logs are displayed:
.......
INFO:tensorflow:Finished batch 312
INFO:tensorflow:Finished batch 313
Traceback (most recent call last):
  File "translator.py", line 370, in <module>
    main(parse_args())
  File "translator.py", line 333, in main
    for item in shard[1]:
IndexError: tuple index out of range

**Comment by Glaceon31** [comment]
Would you provide the detailed setting? That will help us reproduce this error.
