### ISSUE TITLE
checkpoint averaging error.

### ISSUE THREAD

**Issue by Felixgithub2017** [THUNLP-MT/THUMT#74]
When running the checkpoint averaging script, I got the following error.
I am using python 3, I think it is the problem.

Traceback (most recent call last):
  File "thumt/scripts/checkpoint_averaging.py", line 121, in <module>
    tf.app.run()
  File "/home/felix/miniconda3/envs/py37-trans/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "thumt/scripts/checkpoint_averaging.py", line 103, in main
    var_values.iteritems()):
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by Playinf** [comment]
There are 2 solutions:
1. Using Python2 instead of Python3
2. Import the six package, replace `*.iteritems()` with `six.iteritems(*)`
