### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 14:

### ISSUE THREAD

**Issue by HassanNaeemjutt** [THUNLP-MT/THUMT#76]
Traceback (most recent call last):
  File "shuffle_corpus.py", line 64, in <module>
    main(parsed_args)
  File "shuffle_corpus.py", line 30, in main
    data = [fd.readlines() for fd in stream]
  File "shuffle_corpus.py", line 30, in <listcomp>
    data = [fd.readlines() for fd in stream]
  File "C:\Users\Hassan\Anaconda3\envs\finalproject\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 14: character maps to <undefined>

**Comment by GrittyChen** [comment]
@HassanNaeemjutt You can avoid this problem by running the shuffle_corpus.py with python 2.x, and we will fix the bug soon, thanks very much!
