### ISSUE TITLE
你好，请问训练出现KeyError: '<unk>'是怎么回事

### ISSUE THREAD

**Issue by edwardelric1202** [THUNLP-MT/THUMT#88]
数据集是wmt17，按照使用教程预处理好的，在训练一开始的时候就出现了这个问题：
`
Traceback (most recent call last):
  File "/home/cma/cy.he/self_code/fairseq-master/THUMT/thumt/bin/trainer.py", line 512, in <module>
    main(parse_args())
  File "/home/cma/cy.he/self_code/fairseq-master/THUMT/thumt/bin/trainer.py", line 359, in main
    features = dataset.get_training_input(params.input, params)
  File "/home/cma/cy.he/self_code/fairseq-master/THUMT/thumt/data/dataset.py", line 141, in get_training_input
    default_value=params.mapping["source"][params.unk]
KeyError: '<unk>'
`
请问如何解决？是数据集的问题吗？

**Comment by JasmineChen123** [comment]
How to solve this problem?
